services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/rgcassetta/Projects/guy-home-lab/homelab/hass:/config
      - /run/dbus:/run/dbus:ro
      - ./secrets/secrets.yaml:/config/secrets.yaml
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Los_Angeles
    depends_on:
      - mosquitto
      - zigbee2mqtt
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
      - "./mosquitto/secrets:/etc/mosquitto"
    environment:
      - TZ=America/Los_Angeles
    user: "1000:1000"
  zigbee2mqtt:  
    container_name: zigbee2mqtt  
    restart: unless-stopped  
    devices:  
      - /dev/ttyACM0:/dev/ttyACM0  
    ports:  
      - "8080:8080"  
    volumes:  
      - ./zigbee2mqtt/data:/app/data
      - ./secrets/secrets.yaml:/app/data/secrets.yaml
      - /run/udev:/run/udev:ro  
    environment:  
      - TZ=Europe/Amsterdam  
    image: koenkk/zigbee2mqtt
    depends_on:
        - mosquitto
  mqtt2kasa:
    container_name: mqtt2kasa
    build: mqtt2kasa-copy/
    # restart: unless-stopped
    volumes:
      - ./mqtt2kasa-copy:/usr/src/app
    environment:  
      - PYTHONPATH=/usr/src/app
    command: python3 mqtt2kasa/main.py ./data/config.yaml
    depends_on:
        - mosquitto
    stdin_open: true # docker run -i
    tty: true        # docker run -t
